#This code is to simply remove the whitespace from the fasta file generated by the MetaGeneMark gene-finder tool.

import sys
import os

if __name__ == "__main__":
    fasta_file = sys.argv[1]
    fasta_out = sys.argv[2]
    
    fasta_store = []
    with open(fasta_file, "r") as fasta:
        for line in fasta:
            if(line.strip()):
                if(line != "\n"):
                    new_line = line.replace("\t", "")
                    new_line = new_line.replace(" ", "")
                    
                    fasta_store.append(new_line)  #the name seems to apply a tab.  we want the whole split-contig to be its split + original contig name
        
    with open(fasta_out, "w") as file_out:
        for line in fasta_store:
            file_out.write(line)
                